<a href="https://colab.research.google.com/github/NhuY26/BTNum/blob/main/BT_Numpy_s%E1%BB%91_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Bài 1 - Ma trận: Trong Toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu là A ∈ $R_{m×n}$ hay $A_{m×n}$ hay A = $(a_{i,j})_{m×n}$

\begin{align}
        \vec{OA} = \begin{pmatrix}
        a_{1,1} \ \ a_{1,2} \ \ ... \ \ a_{1,n}\\
        a_{2,1} \ \ a_{2,2} \ \ ... \ \ a_{2.n}\\
        \ \ \ \ ⋮ \ \ \ \ \ \ ⋮ \ \ \ \ \ \ ⋮ \ \ \ \ \ \ ⋮ \ \ \ \ \ \ \\
        a_{m,1} \ \ a_{m,2} \ \ ... \ \ a{m,n}
        \end{pmatrix}
    \end{align}
Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ $R^{7×5}$, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [2]:
A = np.random.random([7,5])
print("Ma trận A:\n",A)

Ma trận A:
 [[0.50998325 0.59187324 0.01539616 0.16626057 0.2012503 ]
 [0.57286897 0.10646775 0.85689017 0.26518873 0.69173257]
 [0.55690097 0.65870046 0.70876728 0.52207635 0.65922858]
 [0.56722343 0.93567066 0.96955133 0.82057658 0.78528506]
 [0.27702857 0.56171535 0.46853269 0.347555   0.39452646]
 [0.43734425 0.12015494 0.32109494 0.44376297 0.87454886]
 [0.33117825 0.33203283 0.2985458  0.83000306 0.09146138]]


Bài 2 – Ma trận không (zero matrix): Ma trận $A_{m×n}$ được gọi là ma trận không khi $a_{i,j} = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - $A_{6×7}$. 

Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [3]:
np.zeros([6,7])
print("Ma trận không A:\n",A)

Ma trận không A:
 [[0.50998325 0.59187324 0.01539616 0.16626057 0.2012503 ]
 [0.57286897 0.10646775 0.85689017 0.26518873 0.69173257]
 [0.55690097 0.65870046 0.70876728 0.52207635 0.65922858]
 [0.56722343 0.93567066 0.96955133 0.82057658 0.78528506]
 [0.27702857 0.56171535 0.46853269 0.347555   0.39452646]
 [0.43734425 0.12015494 0.32109494 0.44376297 0.87454886]
 [0.33117825 0.33203283 0.2985458  0.83000306 0.09146138]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ $R_{7×7}$, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [4]:
np.random.randint(1,20,[7,7])
print("Ma trận A:\n",A)

Ma trận A:
 [[0.50998325 0.59187324 0.01539616 0.16626057 0.2012503 ]
 [0.57286897 0.10646775 0.85689017 0.26518873 0.69173257]
 [0.55690097 0.65870046 0.70876728 0.52207635 0.65922858]
 [0.56722343 0.93567066 0.96955133 0.82057658 0.78528506]
 [0.27702857 0.56171535 0.46853269 0.347555   0.39452646]
 [0.43734425 0.12015494 0.32109494 0.44376297 0.87454886]
 [0.33117825 0.33203283 0.2985458  0.83000306 0.09146138]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo $a_{i,i}$ ≠ 0 trong khi các phần tử còn lại $a_{i,j}$ = 0, ∀i ≠ j.

Sử dụng thư viện NumPy, hãy tạo một ma trận chéo $A_{6×6}$ với phần tử nằm trên đường chéo có giá trị là 15. 

Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [5]:
A = np.zeros((6,6))
np.fill_diagonal(A,15)
print("Ma trận chéo A:\n",A)

Ma trận chéo A:
 [[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông $A_{n×n}$ được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.

Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên $A_{8×8}$. 

Gợi ý: sử dụng hàm
numpy.triu(). 

Kết quả xuất ra màn hình.

In [6]:
A = np.random.randint(1,10,[8,8])
print("Ma trận tam giác trên A:\n",np.triu(A,k=0))

Ma trận tam giác trên A:
 [[9 3 6 9 1 7 4 7]
 [0 8 1 1 7 7 5 9]
 [0 0 4 7 9 1 2 4]
 [0 0 0 8 1 8 7 4]
 [0 0 0 0 5 8 4 9]
 [0 0 0 0 0 8 4 8]
 [0 0 0 0 0 0 8 1]
 [0 0 0 0 0 0 0 7]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [7]:
A = np.random.randint(1,10,[8,8])
print("Ma trận tam giác dưới A:\n",np.tril(A,k=0))

Ma trận tam giác dưới A:
 [[2 0 0 0 0 0 0 0]
 [6 5 0 0 0 0 0 0]
 [9 7 9 0 0 0 0 0]
 [8 3 5 4 0 0 0 0]
 [2 5 1 2 6 0 0 0]
 [6 6 9 6 2 2 0 0]
 [1 6 6 4 4 3 4 0]
 [8 2 1 6 4 8 8 8]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị $I_n$ có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
$I_9$
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [8]:
#cách 1

print("Ma trận đơn vị I9:\n",np.identity(9))

#cách 2

print("Ma trận đơn vị I9:\n",np.eye(9))

Ma trận đơn vị I9:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Ma trận đơn vị I9:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:
- Phép cộng ma trận: $A_{m×n} + B_{m×n} = C_{m×n}$. Hãy sinh ngẫu nhiên 2 ma trận có kích thước
6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.
- Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 1 ma trận có kích thước
5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất
ra màn hình.
- Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.
- Phép nhân 2 ma trận: $A_{m×n} + B_{m×n} = C_{m×n}$. Hãy sinh ngẫu nhiên 2 ma trận $A_{5×7} và B_{7×3}$,
tiến hành nhân 2 ma trận này để thu được ma trận $C_{5×3}$. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()
- Ma trận khả nghịch: ma trận vuông $A_{n×n}$ 
gọi là khả nghịch (hay không suy biến) nếu tồn
tại một ma trận vuông $B_{n×n}$ sao cho A ∙ B = $I_n$ . Khi này, B được gọi là ma trận nghịch
đảo của A và ký hiệu là A
−1
. Cho ma trận $A_{5×7}$, hãy tính ma trận khả nghịch của A. 

Gợi ý: sử dụng hàm numpy.linalg.inv()

In [9]:
#cộng hai ma trận

A = np.random.randint(1,10,[6,7])
B = np.random.randint(1,10,[6,7])
print("A+B:\n",A+B)

#Nhân vô hướng

A = np.random.randint(1,5,[5,8])
print(A)
n = int(input("Nhân ma trận với: "))
print("Kết quả của phép nhân vô hướng A với",n,"là\n",A*n)

#Chuyển vị

A = np.random.randint(1,10,[3,7])
print("Ma trận ban đầu:\n",A)
print("Chuyển vị:\n",A.T)

#Nhân hai ma trận

A = np.random.randint(1,5,[5,7])
print("Ma trận A:\n", A)
B = np.random.randint(1,5,[7,3])
print("Ma trận B:\n", B)
print("Nhân hai ma trận A và B:\n",A.dot(B))

#Ngoài ra: A @ B cũng là phép nhân hai ma trận A và B

#Ma trận nghịch đảo

A = np.random.randint(1,5,[5,5])
A_i = np.linalg.pinv(A)
print("Ma trận ban đầu\n",A)
print("Ma trận nghịch đảo\n",A_i)

A+B:
 [[ 2  8 12 11 11  5 16]
 [ 8 18  8  7 10 10  5]
 [12  8 14 14  7 12  3]
 [ 9 10  6  4 12 16  7]
 [ 5  6  8 10 12 16  8]
 [ 5 10 16 13  6  8 16]]
[[4 1 3 1 1 3 4 4]
 [1 2 3 1 4 2 3 3]
 [2 1 2 1 3 1 4 1]
 [3 4 3 3 2 1 3 2]
 [4 1 2 2 2 1 1 3]]
Nhân ma trận với: 3
Kết quả của phép nhân vô hướng A với 3 là
 [[12  3  9  3  3  9 12 12]
 [ 3  6  9  3 12  6  9  9]
 [ 6  3  6  3  9  3 12  3]
 [ 9 12  9  9  6  3  9  6]
 [12  3  6  6  6  3  3  9]]
Ma trận ban đầu:
 [[3 3 3 6 7 9 9]
 [9 5 5 3 8 2 5]
 [8 2 1 9 9 8 9]]
Chuyển vị:
 [[3 9 8]
 [3 5 2]
 [3 5 1]
 [6 3 9]
 [7 8 9]
 [9 2 8]
 [9 5 9]]
Ma trận A:
 [[4 2 4 4 2 1 3]
 [3 4 4 1 1 1 4]
 [2 2 4 2 3 3 1]
 [4 1 4 1 4 2 4]
 [4 3 4 3 2 3 1]]
Ma trận B:
 [[4 3 3]
 [2 4 3]
 [2 4 3]
 [1 4 3]
 [1 3 3]
 [1 1 3]
 [3 1 1]]
Nhân hai ma trận A và B:
 [[44 62 54]
 [43 53 46]
 [31 51 49]
 [45 54 52]
 [41 62 58]]
Ma trận ban đầu
 [[3 1 1 4 4]
 [3 3 4 3 3]
 [1 3 4 2 4]
 [1 4 3 2 2]
 [3 2 2 2 3]]
Ma trận nghịch đảo
 [[-0.15789474  0.12631579 -0.24210526 -0.115

Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau
- Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1
vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
- Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [10]:
#Vector hàng

A = np.random.randint(1,10,[1,8])
print(A)
A.shape

#Vector cột

A = np.random.randint(1,10,[8,1])
print(A)
A.shape

[[2 5 9 2 5 4 9 2]]
[[9]
 [5]
 [8]
 [9]
 [5]
 [8]
 [9]
 [1]]


(8, 1)

In [13]:
#bài10
import numpy as np
A = np.random.randint(1,10,[3,3])
y = np.random.randint(1,5)
A_i = np.linalg.pinv(A)
x = np.dot(A_i, y)
print(x)

[[ 0.33333333 -2.22222222  1.44444444]
 [-0.16666667  0.61111111  0.27777778]
 [ 0.16666667  1.38888889 -1.27777778]]
