<a href="https://colab.research.google.com/github/NhuY26/BTNum/blob/main/BT_Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.
\begin{align}
\end{align} 
numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

- numpy.apply_along_axisLà hàm cho phép ta sử dụng hàm theo từng chiều.
- func1d : Hàm thực hiện
- axis : chọn chiều cần thực hiện
- arr : mảng cần xử lí
- *args và **kwargs đều chủ yếu được sử dụng trong định nghĩa. Hai cú pháp đặc biệt này giúp chúng ta có thể truyền bao nhiêu tham số vào hàm cũng được.
Hai hàm này thông thường ta thường bỏ qua vì trong điều kiện bình thường không cần sử dụng.

In [2]:
a = np.random.randint(1,100,[15,17])
a

array([[53, 79, 52, 88, 31, 11, 83, 25, 17, 91, 79, 12, 39, 87,  9, 94,
        11],
       [19,  6, 75, 80, 48,  1,  9, 89, 12, 59, 57, 83, 71, 21, 76, 79,
        37],
       [78, 15,  9, 44, 45, 91, 37, 18, 74, 93, 53, 40, 27, 73, 50, 89,
        16],
       [58, 90,  4, 52, 33, 69, 33, 25, 45, 25, 63, 49, 36, 30, 71, 76,
        56],
       [53, 63, 48, 30, 55, 73, 99, 26, 19,  8,  3, 92, 76, 71, 41, 75,
        41],
       [47, 46,  4, 34, 71, 26, 23, 79, 80, 66, 44, 65, 14, 64, 83, 82,
        66],
       [99, 69, 71, 22, 56, 26, 46, 24, 16,  8, 57, 97,  5, 28, 44, 34,
        95],
       [41, 61, 99, 97, 66, 23, 94, 93, 42, 93, 17, 68, 60, 12, 42, 39,
         5],
       [26, 51, 45, 99, 13, 21, 18, 90, 95, 38, 68, 24, 76, 86, 71, 12,
        78],
       [71, 97, 84, 72, 83, 87, 14, 58, 79, 16,  6, 36, 61, 41,  2, 45,
        75],
       [32, 84, 74, 39,  4, 12, 80, 55, 95, 50, 44, 26, 53, 73, 28,  1,
        31],
       [33, 54, 11, 83, 67, 11, 28, 88,  5, 89, 90, 71, 24, 43,  

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [3]:
def tim_gia_tri_lon_nhat(a):
    return np.max(a)

def main():
    print("\nMax : \n", np.apply_along_axis(tim_gia_tri_lon_nhat, 1, a));

if __name__ == '__main__':
    main();


Max : 
 [94 89 93 90 99 83 99 99 99 97 95 90 89 99 93]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def tim_gia_tri_nho_nhat(a):
  return np.min(a)

def main():
    print("\nMin : \n", np.apply_along_axis(tim_gia_tri_nho_nhat,0,a));

if __name__ == '__main__':
    main();


Min : 
 [19  6  4 22  4  1  9 18  5  8  3 12  5 12  2  1  5]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [5]:
def tinh_tong(a):
    return np.sum(a)

def main():
    print("Sum: \n",np.apply_along_axis(tinh_tong,1,a))

if __name__ == '__main__':
    main();


Sum: 
 [861 822 852 815 873 894 797 952 911 927 781 860 909 813 973]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [6]:
def tinh_tong_2(vector_a):
    sum  = 0
    for i in range(len(vector_a)):
      if (i % 2 != 0):
        sum  = sum +vector_a[i]
    return sum

def main():
    print("Sum: \n",np.apply_along_axis(tinh_tong_2, 1, a))

if __name__ == '__main__':
    main();

Sum: 
 [487 418 463 416 438 462 308 486 421 452 340 527 497 470 482]
