<a href="https://colab.research.google.com/github/NhuY26/BTNum/blob/main/BT_NumPy_s%E1%BB%91_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
import random

bài 1: Xét không gian $R^3$ một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

sử dụng các thư viện sau:


*   numpy để tính toán số học, vector, ma trận 


*   math để tính toán các hàm toán học 
*   random để thực hiện sinh số ngẫu nhiên







In [ ]:
a = np.array([5,7,14])
print("a: \n", a)
print("số chiều không gian của điểm a: ", a.ndim)

a: 
 [ 5  7 14]
số chiều không gian của điểm a:  1


bài 2: Mở rộng không gian lên  R15 , điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [ ]:
a = np.array(np.arange(16))
print("a: \n", a)


a: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: trong không gian $R^n$, xét vector $\vec{OA}$ với O là điểm gốc tọa độ và A là điểm có tọa độ tổng
quát là($a_1, a_2,...,a_n)$. vector $\vec{OA}$ lúc này được viết dưới dạng vector cột (column vector) là: 
\begin{align}
        \vec{OA} = \begin{pmatrix}
        a_1 \\
        a_2 \\
        ⋮ \\
        a_n
        \end{pmatrix}
    \end{align}
Hay ở dạng vector hàng (row vector) là:
\begin{align}
        {\vec{OA} = \begin{pmatrix}
        {a_1 \\
        a_2 \\
        ⋮ \\
        a_n}
        \end{pmatrix}}^T = [a_1 \ a_2\ ... \ a_n]
    \end{align} 
Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian $R^n$ với n là số nguyên dương
được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [ ]:
n = int(input("nhap n: "))

# sinh số ngẫu nhiên đối với số nguyên 

a = np.random.randint(low=-10, high=10, size=(1,n))
print("a: \n",a)

nhap n: 4
a: 
 [[-9  0  3  0]]


Bài 4: trong không gian $R^3$, xét vector $\vec{OA}$

> Văn bản được thụt lề


\begin{align}
        \vec{OA} = \begin{pmatrix}
        7 \\
        -5 \\
        8 
        \end{pmatrix}
    \end{align}
Hãy viết chương trình tính chiều dài của vector $\vec{OA}$ , biết công thức tổng quát để tính chiều dài
vector $\vec{OA}$ trong không gian $R^n$
là:
\begin{align}
||\vec{OA}|| = \sqrt{a^2_1 + a^2_2 + ... + a^2_n}
\end{align}
lưu ý: sử dụng numpy

In [ ]:
OA = np.array([7,-5,8])
print(OA)
chieu_dai_vector_OA = np.sqrt((OA[0])**2 + (OA[1])**2 + (OA[2])**2)
print("Chiều dài vector OA là: ", chieu_dai_vector_OA)

[ 7 -5  8]
Chiều dài vector OA là:  11.74734012447073


bài 5:Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector $\vec{AB}$ và tính

chiều dài của vector $||\vec{OA}||$ này . 

Lưu ý: sử dụng Numpy.

In [ ]:
n = int(input("Nhập n: "))
A = np.random.randint(low=-10, high=10, size=(1,n))
print(A)
B = np.random.randint(low=-10, high=10, size=(1,n))
print(B)

vector_AB = B-A
print("Vector AB là: ", vector_AB)

chieu_dai_vector_AB = np.sqrt((vector_AB[0][0])**2 + (vector_AB[0][1])**2 + (vector_AB[0][2])**2)
print("Chiều dài vector AB là: ", chieu_dai_vector_AB)

Nhập n: 5
[[ 3 -5  0 -8 -9]]
[[-9  0  3 -2 -9]]
Vector AB là:  [[-12   5   3   6   0]]
Chiều dài vector AB là:  13.341664064126334


bài 6:Tích vô hướng của 2 vector $\vec{a}$ & $\vec{b}$ (dot product hoặc inner product hoặc scalar product) được
tính theo công thức tổng quát là:

$\vec{a}$ . $\vec{b}$ = ${a_1b_1 + a_2b_2 +...+ a_3b_3}$

Trong không gian $R^n$ , hãy sinh ngẫu nhiên 2 vector $\vec{a}$ & $\vec{b}$ và tính tích vô hướng của 2 vector này.

Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.

Gợi ý: sử dụng hàm numpy.inner()

In [14]:
n = int(input("Nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print("vector a là: ", a)

b = np.random.randint(low=-10, high=10, size=(1,n))
print("vector b là: ", b)

tich_vo_huong = np.inner(a, b)
print("tích vô hướng của 2 vector a và b là: ", tich_vo_huong)

Nhập n: 3
vector a là:  [[ -4 -10   4]]
vector b là:  [[ 0  4 -6]]
tích vô hướng của 2 vector a và b là:  [[-64]]


bài 7: Tích hữu hướng (cross product) của 2 vector $\vec{a}$ & $\vec{b}$ được tính theo công thức tổng quát là:

$\vec{a}$ × $\vec{b}$ = $||\vec{a}||  ||\vec{b}||$ sin(θ)

Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 vector $\vec{a}$ & $\vec{b}$ và tính tích hữu hướng của 2 vector này.

Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.

Gợi ý: sử dụng hàm numpy.cross()

In [18]:
n = int(input("Nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print("vector a là: ", a)

b = np.random.randint(low=-10, high=10, size=(1,n))
print("vector b là: ", b)

tich_huu_huong = np.cross(a, b)
print("tích hữu hướng của 2 vector a và b là: ", tich_huu_huong)

Nhập n: 3
vector a là:  [[ 8  7 -2]]
vector b là:  [[ 6 -1  7]]
tích hữu hướng của 2 vector a và b là:  [[ 47 -68 -50]]


bài 8: Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được
thực hiện thông qua thao tác a.T

Hãy viết chương trình sinh ngẫu nhiên một vector $\vec{a}$ trong không gian $R^n$, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector $\vec{a}$ và chuyển vị của vector $\vec{a}$ .

In [20]:
n = int(input("Nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print("vector a là: ", a, sep = '\n')

print("Chuyển vị của vector a là: ", a.T, sep = '\n')

Nhập n: 5
vector a là: 
[[ 2 -2  0  2  5]]
Chuyển vị của vector a là: 
[[ 2]
 [-2]
 [ 0]
 [ 2]
 [ 5]]


bài 9:
Kết hợp cấu trúc list với Numpy: Xét 2 cấu trúc list dưới đây:
1. a = [1, 2, 3, 4, 5]
2. b = [[1], [2], [3], [4], [5]]
Hãy:
- Xuất a và b ra màn hình
- Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
- Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [21]:
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]

aa = np.array(a)
bb = np.array(b)

print(a)
print(b)

print("vector a là: ", aa)
print("vector b là: ", bb, sep = '\n')

print("Chuyển vị của vector a là: ", aa.T)
print("Chuyển vị của vector b là: ", bb.T)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
vector a là:  [1 2 3 4 5]
vector b là: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Chuyển vị của vector a là:  [1 2 3 4 5]
Chuyển vị của vector b là:  [[1 2 3 4 5]]


Bài 10: Trong không gian $R^n$, hãy sinh ngẫu nhiên vector $\vec{a}$ và $\vec{b}$ , n là số nguyên dương nhập vào từ bàn phím. 

Hãy:


- Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình
- Thực hiện phép cộng 2 vector: a + b⃗ và xuất kết quả ra màn hình.

In [22]:
n = int(input("nhập n: "))

a = np.random.randint(low=-10, high=10, size=(1,n))
print(a)
b = np.random.randint(low=-10, high=10, size=(1,n))
print(b)

m = int(input("nhập m: "))

print("a*m: \n", a*m)
print("a+b là: \n", a+b)

nhập n: 2
[[-10   7]]
[[7 5]]
nhập m: 6
a*m: 
 [[-60  42]]
a+b là: 
 [[-3 12]]
